# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: ☕ Serviço de App Web Backend Java na Azure CI/CD

on:
  push:
    branches:
      - feature/integracao-azure-web-app
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest 
    permissions:
      contents: read 

    env: 
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_URL: ${{ secrets.DB_URL }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      AZURE_ACCOUNT_NAME: ${{ secrets.AZURE_ACCOUNT_NAME }}
      AZURE_CONTAINER_NAME: ${{ secrets.AZURE_CONTAINER_NAME }}
      AZURE_SAS_TOKEN: ${{ secrets.AZURE_SAS_TOKEN }}
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Set up Java version 
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft' 
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install
        working-directory: ./estoque-de-produtos-crud 
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: './estoque-de-produtos-crud/target/*.jar'

      - name: Upload Surefire Reports 
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: surefire-reports
          path: './estoque-de-produtos-crud/target/surefire-reports/'
          
  deploy:
    runs-on: ubuntu-latest 
    needs: build 
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write 
      contents: read 
      
    steps:
      - name: Download artifact from build job 
        uses: actions/download-artifact@v4
        with:
          name: java-app
          
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_80FBD64D5A18485E934D320140BAEA51 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F7D35A08F1744C988CA90AD506795DC8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A8FF7D02F156413791F48D62EF441D90 }}

      - name: Deploy to Azure Web App 
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'i9-server-backend' 
          slot-name: 'Production'
          package: 'estoque-de-produtos-0.0.1-SNAPSHOT.jar'
